### ISSUE TITLE
Output a minimal x64 binary

### ISSUE THREAD

**Issue by dcecile** [pentagram-lang/pentagram-gen4-python#1]
### Research
- [x] Read over [Teensy ELF](http://www.muppetlabs.com/~breadbox/software/tiny/teensy.html) article
- [x] Find out if x64 instructions align to 4 bytes
- [x] Find out the performance benefits of x64 over x86
- [x] Research x64 best practices
- [x] Learn how to write x64 with NASM

### Design
- [x] Use NASM to construct a minimal x64 ELF binary
- [x] Assign a section name to the binary's executable code
- [x] Make the binary a [PIE](https://en.wikipedia.org/wiki/Position-independent_code#PIE)
- [x] Make program load just the executable code
- [x] Separate executable and non-executable pages
- [x] Pick a folder structure for this project

### Tasks
- [x] Create and output a single blob with all raw binary data
- [x] Test compiled output execution on tmpfs
- [x] Document with comments
- [x] Use `main` method
- [x] Split out helper methods

**Comment by dcecile** [comment]
> AMD64 technology instructions are encoded as byte strings of variable length.

Definitely not aligned to words or whatever.

**Comment by dcecile** [comment]
Benefits of x64 are more general purpose registers, more advanced single-instruction multiple-data operations, and access to more (virtual) memory. This can result in [significant gains](https://www.phoronix.com/scan.php?page=article&item=ubuntu-1710-x8664&num=1) depending (in general) on how much number crunching is done in the application.

**Comment by dcecile** [comment]
I only found one area of advice for efficient x64 vs. x86 assembly:

1. For instruction size optimization, you can use the original 8 registers for 32-bit (or less) operations, you can use 64-bit registers for address base and index operands, and you can use instruction-pointer-relative addressing

(Normal x86 assembly performance guidelines still apply to x64.)

**Comment by dcecile** [comment]
"Basic" ELF file created using NASM: https://gist.github.com/dcecile/82e672a0994043a1194012029c3172f1

### Features:
- Linux-only
- x64 instructions and syscalls
- Position-independent executable
- Separate code and data segments
- Annotated sections for `objdump` debugging

**Comment by dcecile** [comment]
Folder structure is like this:

```
/README.md
/LICENSE.md
/main.tacit
/parser/index.tacit
/parser/keywords.tacit
/parser/keywords.test.tacit
/compiler/x64.tacit
```

**Comment by dcecile** [comment]
Different default hello world executable sizes:

- Rust: 650,771 bytes (with allocator)
- C: 8,551 bytes
- C++: 9,168 bytes
- Go: 202,9206 bytes (with libraries, GC)
- Haskell: 436,496 bytes (with runtime system)
- Teensy-inspired with section header table and strings: 508 bytes

**Comment by dcecile** [comment]
Done, [main.tacit](https://github.com/tacit-lang/tacit/blob/34910dbc64b11662e841e16a47105db2c7607b80/main.tacit) interpreted to generate 513-byte "Hello, Tacit world!" Linux ELF x64 executable
