### ISSUE TITLE
Interpret testing

### ISSUE THREAD

**Issue by dcecile** [pentagram-lang/pentagram-gen4-python#4]
The final goal of the interpreter will to build up tests written in Pentagram. Then once those tests are passing and the compiler is self-compiling, the interpreter can be retired.

This could be a special mode written using [watchdog](https://github.com/gorakhargosh/watchdog). Pure custom, for better latency and to start experimenting with output format. (And to more easily gradually move the test framework into Pentagram code.)

### Tasks

- [x] Make [asciinema](https://asciinema.org/) of [gen 2](https://github.com/tacit-lang/tacit-gen2-scala) JVM REPL
- [x] Make [asciinema](https://asciinema.org/) of [Outerline](https://github.com/dcecile/outerline) tests
- [x] Update [testing ideas](https://github.com/tacit-lang/tacit-ideas/blob/master/syntax/testing.md)
- [x] Switch to [pip-tools](https://github.com/jazzband/pip-tools) with hashes
- [x] Set up internal-use CLI
  - [x] Precommit
  - [x] Freeze
  - [x] Check
    - [x] Style, lint, etc.
    - [x] Frozen deps
- [x] Set up Github Actions
- [x] Convert `typing` usages to use [PEP 585](https://peps.python.org/pep-0585/) and [PEP 604](https://peps.python.org/pep-0604/)
- [x] Rename all "Tacit" references
- [x] Automatically convert Python method names and parameters
- [x] Update syntax and data structures to current thinking
  - [x] Switch `TBit` to `TInteger`
  - [x] Switch `blob` to `arr`
  - [x] Switch `/=` to `>>`
  - [x] Prevent arbitrary block starts
  - [x] Use one shared expression stack
- [ ] Collect and run tests
- [ ] Trigger a crash on assertion failure
- [ ] Watch for changes
- [ ] Display advanced live test results
- [ ] Allow basic test execution/introspection control

**Comment by dcecile** [comment]
Dynamic PyTest example:

```py
def test_a():
    print('test_a' in globals())
    assert False

def define():
    for n in 'bcdef':
        def x():
            assert 1 == 0
        x.__name__ = f'test_{n}'
        globals()[x.__name__] = x

define()
```

(Results probably not that much more readable than using `parametrize` with a path argument.)

**Comment by fuckurs** [comment]
​            ​"pytest-watch"​,
