### ISSUE TITLE
Interpret control flow

### ISSUE THREAD

**Issue by dcecile** [pentagram-lang/pentagram-gen4-python#5]
### Tasks

- [ ] Add pass that builds environments
- [ ] Parse Pentagram method type annotations for arity
- [ ] Parse Python method type annotations for arity
- [ ] Remove automatic conversion of Python methods?
- [ ] Add abilty for methods to accept expression trees
- [ ] Add abilty for methods to accept other metadata
  - [ ] File name and line number
  - [ ] Preceding comment
- [ ] Parse multi-part methods
- [ ] Change exection from stack to expression
- [ ] Implement control flow
  - [ ] `or and nor nand`
  - [ ] `iif`
  - [ ] `if elif else`
  - [ ] `for else`
  - [ ] `while else`
- [ ] Implement other meta uses
  - [ ] `test`
  - [ ] `assert`
  - [ ] `dbg`
